### ISSUE TITLE
Only New Pleroma Posts Crawled

### ISSUE THREAD

**Issue by ibrokemypie** [Lynnesbian/FediBooks#22]
**What happened?**
When you source from pleroma accounts, only the last ten or so posts arer cached, and then any new ones

**How did it happen?**
1. Add pleroma account to learn from
2. Wait

**Where did it happen?**
Please copy and paste the URL here.
https://fedibooks.com/bot/accounts/@piebooks@pl.ohno.host

**Expected behavior**
All posts eventually crawled

**Error message**
Did FediBooks give you an error message? If so, paste the message here.
None

**Further comments**
You can add more info here if you'd like.
The outbox json has a "next" key that holds a link to a new outbox with the next 10 posts, and a new next.

**Comment by BlueRaccoonTech** [comment]
I don't know if the post-crawling code has been changed from when I last played around with it - if not, I believe the issue lies around the Flake ID system that Pleroma uses for posts (the code doesn't quite handle them properly.)

**Comment by Lynnesbian** [comment]
The code has been updated to be ID-agnostic. I have no idea why this happens. I've looked into how Pleroma does outboxes and it seems as though it only exposes the last ten or so posts, with the "next" link not doing anything. I'll take another look into it.

**Comment by Lynnesbian** [comment]
This should be solved now - it was a [bug](https://git.pleroma.social/pleroma/pleroma/merge_requests/1700) in Pleroma. You'll need to update to the latest version of Pleroma for the fix to work for you. Unfortunately, it still won't be able to scrape all your posts, because Pleroma doesn't expose a way to get a user's earliest post, but it'll do a better job. In future, newly added Pleroma accounts will have more of their posts downloaded
